//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserPermission
    {
        [Key]
        public int Id_UserPermission { get; set; }
        public int Id_User { get; set; }
        public int Id_Permission { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserR UserR { get; set; }
    }
}
